#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Enables tab completion in bash
complete -cf sudo

# Prefer vi mode
set -o vi

# Development
source ~/bin/share/chruby/share/chruby/chruby.sh
source ~/bin/share/chruby/share/chruby/auto.sh

# Better manage local friends
me=${BASH_SOURCE[0]}
me=$([ -h $me ] && echo $(readlink $me) || echo $me)
dir=$(dirname $me)

source $dir/aliases
source $dir/exports
source $dir/functions
source $dir/prompts
