#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Enables tab completion in bash
#complete -cf sudo

# Prefer vi mode
set -o vi

# Disable beep
#set b off
#xset b off

# Better manage local friends
me=${BASH_SOURCE[0]}
me=$([ -h $me ] && echo $(readlink $me) || echo $me)
dir=$(dirname $me)

source $dir/bashrc.manjaro
source $dir/aliases
source $dir/exports
source $dir/prompts

for f in `ls $dir/funcs.d`; do
  source $dir/funcs.d/$f
done

source /usr/share/nvm/init-nvm.sh
