set nocompatible " be iMproved
filetype off     " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle (required!)
Bundle 'gmarik/vundle'


" Ruby
Bundle 'tpope/vim-rails.git'


" My Bundles here:
"
" original repos on github
"Bundle 'tpope/vim-fugitive'
"Bundle 'Lokaltog/vim-easymotion'
"Bundle 'rstacruz/sparkup', {'rtp': 'vim/'}

" vim-scripts repos
Bundle 'Wombat'
Bundle 'CSApprox'

"Bundle 'FuzzyFinder'
" non github repos
"Bundle 'git://git.wincent.com/command-t.git'
" ...

filetype plugin indent on     " required!
"
" Brief help
" :BundleList          - list configured bundles
" :BundleInstall(!)    - install(update) bundles
" :BundleSearch(!) foo - search(or refresh cache first) for foo
" :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
"
" see :h vundle for more details or wiki for FAQ
" NOTE: comments after Bundle command are not allowed..
"

"Theming
syntax enable
colorscheme wombat
set t_Co=256

"Tabbing
set expandtab
set smarttab
set softtabstop=2
set tabstop=2
set shiftwidth=2

"Turn off backup
set nobackup
set nowritebackup
set noswapfile

"Encoding
set encoding=utf-8
set fileencoding=utf-8

"Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

"Misc appearance
set number
set colorcolumn=80
set ruler
set nowrap

"Indenting
set autoindent
set smartindent

"Disable mouse
set mouse-=a

"Backspacing
set backspace=indent,eol,start

"Vim's history
set viminfo='20,\"1000 "
set history=50

