#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Synchronizes the two copy/paste buffers mainly used by X applications
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

# Use custom key mappings
xmodmap -e "remove Lock = Caps_Lock"
xmodmap ~/etc/X/Xmodmap

# Ensure ~/.Xresources takes effect
xrdb -merge ~/.Xresources

# Wallpaper
feh --bg-fill ~/etc/X/pics/00.jpg

# Disables all beep
xset b off

# Start windows manager
exec ~/bin/dwm
#exec i3
# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice
