#!/bin/bash
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Local variables
me=${BASH_SOURCE[0]}
me=$([ -h $me ] && echo $(readlink $me) || echo $me)
dir=$(dirname $me)

# Synchronizes the two copy/paste buffers mainly used by X applications
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

# Use custom key mappings
xmodmap -e "remove Lock = Caps_Lock"
xmodmap $dir/share/keymaps

# Ensure ~/.Xresources takes effect
xrdb -merge ~/.Xresources

# Wallpaper
feh --bg-fill $dir/share/00.jpg

# Disables all beep
xset b off

# Start conky
conky --daemonize

# Start windows manager
exec ~/bin/dwm
#exec i3
# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice
