#!/bin/bash
#
# ~/.xinitrc
#
## Executed by startx (run your window manager from here)
#
#if [ -d /etc/X11/xinit/xinitrc.d ]; then
#  for f in /etc/X11/xinit/xinitrc.d/*; do
#    [ -x "$f" ] && . "$f"
#  done
#  unset f
#fi
#
## Local variables
ME=${BASH_SOURCE[0]}
ME=$([ -h $ME ] && echo $(readlink $ME) || echo $ME)
DIR=$(dirname $ME)
#
## Chinese input
#export GTK_IM_MODULE=ibus
#export XMODIFIERS=@im=ibus
#export QT_IM_MODULE=ibus
#ibus-daemon --daemonize
#
## Synchronizes the two copy/paste buffers mainly used by X applications
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

## Use custom key mappings
#xmodmap -e "remove Lock = Caps_Lock"
#xmodmap $dir/share/keymaps
#
## Ensure ~/.Xresources takes effect
#xrdb -merge ~/.Xresources
#
## Wallpaper
feh --bg-fill $DIR/share/wallpaper.jpg

## Disables all beep
#xset b off

## Fake WM
#wmname LG3D

# Key bindings
xbindkeys --poll-rc

# Handle lock screen
xss-lock -- $DIR/bin/lockscreen &

# Disable touchpad (see $ xinput list)
#xinput set-prop 11 "Device Enabled" 0
/usr/bin/synclient TouchpadOff=1

# Start Conky
conky --config ~/etc/conky/current --daemonize

# Start windows manager
exec i3
#exec xfdesktop
#exec ~/bin/gen/dwm
# exec gnome-session
# exec startkde
# exec startxfce4
# ...or the Window Manager of your choice
